### ISSUE TITLE
Bug Ensure Contraint Wrong hyphenated (?)

### ISSUE THREAD

**Issue by wbombardellis** [bombardellif/acrostics-generator#8]
How to reproduce:
Run the complete algorithm(_With WordInsertionDeleteOperation_) with input text "Text/Traurigkeit.txt" and acrostic "Iwh".

__Orginal text:__
Im Englischen bedeutet blau sein so etwas wie traurig sein,
weltbekannt ist zum Beispiel die Musikrichtung Blues. das ist traurig
aber Im Deutschen hat blau sein allerdings eine ganz andere Bedeutung.
Wenn jemand eine feucht-fröhliche Party feiert (also eine, auf der
viel Alkohol getrunken wird), dann ist er hinterher wahrscheinlich
blau. Blau sein bedeutet im Deutschen nämlich betrunken sein.

__Result Text after first "WordInsertionOperation" application:__
Im Englischen bedeutet blau sein so etwas wie traurig sein,
__welt-
tbekannt__ ist zum Beispiel die Musikrichtung Blues. das ist echt traurig-
gaber Im Deutschen hat blau sein allerdings eine ganz andere Bedeut-
tung.Wenn jemand eine feucht-fröhliche Party feiert (also eine, auf
derviel Alkohol getrunken wird), dann ist er hinterher wahrscheinlichblau. Blau sein bedeutet im Deutschen nämlich betrunken sein.

**Comment by wbombardellis** [comment]
Error seems to have changed

ORIGINAL TEXT:
Im Englischen bedeutet blau sein so etwas wie traurig oder deprimiert
sein, weltbekannt ist die Musikrichtung Blues. Das ist traurig aber.
Im Deutschen hat blau sein allerdings eine ganz andere Bedeutung. Wenn
jemand eine feucht-fröhliche Party feiert (also eine, auf der viel
Alkohol getrunken wird), dann ist er hinterher wahrscheinlich blau.
Blau sein bedeutet im Deutschen nämlich betrunken sein.



Progress!!
Im Englischen bedeutet blau sein so etwas wie traurig oder deprimiert
sein, weltbekannt ist die Musikrichtung Blues. Das ist traurig aber.
Im Deutschen hat blau sein allerdings eine ganz andere Bedeutung. Wenn
jemand eine feucht-fröhliche Party feiert (also eine, auf der viel
Alkohol getrunken wird), dann ist er hinterher wahrscheinlich blau.
Blau sein bedeutet im Deutschen nämlich betrunken sein.

NetSpeakApi (1): * im englischen bedeutet blau
NetSpeakApi (2): im * englischen bedeutet blau
NetSpeakApi (3): im englischen * bedeutet blau
NetSpeakApi (4): englischen bedeutet * blau sein
NetSpeakApi (5): bedeutet blau * sein so
NetSpeakApi (6): blau sein * so etwas
NetSpeakApi (7): sein so * etwas wie
NetSpeakApi (8): so etwas * wie traurig
NetSpeakApi (9): etwas wie * traurig oder
NetSpeakApi (10): wie traurig * oder deprimiert
NetSpeakApi (11): traurig oder * deprimiert sein
NetSpeakApi (12): oder deprimiert * sein weltbekannt
NetSpeakApi (13): deprimiert sein * weltbekannt ist
NetSpeakApi (14): sein weltbekannt * ist die
NetSpeakApi (15): weltbekannt ist * die musikrichtung
NetSpeakApi (16): ist die * musikrichtung blues
NetSpeakApi (17): die musikrichtung * blues das
NetSpeakApi (18): musikrichtung blues * das ist
NetSpeakApi (19): blues das * ist traurig
NetSpeakApi (20): das ist * traurig aber
NetSpeakApi (21): ist traurig * aber im
NetSpeakApi (22): traurig aber * im deutschen
NetSpeakApi (23): aber im * deutschen hat
NetSpeakApi (24): im deutschen * hat blau
NetSpeakApi (25): deutschen hat * blau sein
NetSpeakApi (26): hat blau * sein allerdings
NetSpeakApi (27): blau sein * allerdings eine
NetSpeakApi (28): sein allerdings * eine ganz
NetSpeakApi (29): allerdings eine * ganz andere
NetSpeakApi (30): eine ganz * andere bedeutung
NetSpeakApi (31): ganz andere * bedeutung wenn
NetSpeakApi (32): andere bedeutung * wenn jemand
NetSpeakApi (33): bedeutung wenn * jemand eine
NetSpeakApi (34): wenn jemand * eine feuchtfrhliche
NetSpeakApi (35): jemand eine * feuchtfrhliche party
NetSpeakApi (36): eine feuchtfrhliche * party feiert
NetSpeakApi (37): feuchtfrhliche party * feiert also
NetSpeakApi (38): party feiert * also eine
NetSpeakApi (39): feiert also * eine auf
NetSpeakApi (40): also eine * auf der
NetSpeakApi (41): eine auf * der viel
NetSpeakApi (42): auf der * viel alkohol
NetSpeakApi (43): der viel * alkohol getrunken
NetSpeakApi (44): viel alkohol * getrunken wird
NetSpeakApi (45): alkohol getrunken * wird dann
NetSpeakApi (46): getrunken wird * dann ist
NetSpeakApi (47): wird dann * ist er
NetSpeakApi (48): dann ist * er hinterher
NetSpeakApi (49): ist er * hinterher wahrscheinlich
NetSpeakApi (50): er hinterher * wahrscheinlich blau
NetSpeakApi (51): hinterher wahrscheinlich * blau blau
NetSpeakApi (52): wahrscheinlich blau * blau sein
NetSpeakApi (53): blau blau * sein bedeutet
NetSpeakApi (54): blau sein * bedeutet im
NetSpeakApi (55): sein bedeutet * im deutschen
NetSpeakApi (56): bedeutet im * deutschen nmlich
NetSpeakApi (57): im deutschen * nmlich betrunken
NetSpeakApi (58): deutschen nmlich * betrunken sein
NetSpeakApi (59): deutschen nmlich betrunken * sein
NetSpeakApi (60): deutschen nmlich betrunken sein *

Progress!!
Im Englischen bedeutet blau in der rolle auf der bühne stehen so etwas
wie traurig oder deprimiertsein, weltbekannt ist die Musikrichtung Bl-
ues. Das ist traurig aber.Im Deutschen hat blau sein allerdings eine -
ganz andere Bedeutung. Wennjemand eine feucht-fröhliche Party feiert -
(also eine, auf der vielAlkohol getrunken wird), dann ist er hinterher
wahrscheinlich blau.Blau sein bedeutet im Deutschen nämlich betrunke
sein.

NetSpeakApi (61): im deutschen * nmlich betrunkensein
NetSpeakApi (62): im deutschen nmlich * betrunkensein
NetSpeakApi (63): im deutschen nmlich betrunkensein *
NetSpeakApi (64): blues das * ist echt
NetSpeakApi (65): das ist * echt traurig
NetSpeakApi (66): ist echt * traurig aberim
NetSpeakApi (67): echt traurig * aberim deutschen
NetSpeakApi (68): traurig aberim * deutschen hat
NetSpeakApi (69): aberim deutschen * hat blau
NetSpeakApi (70): ganz andere * bedeutung wennjemand
NetSpeakApi (71): andere bedeutung * wennjemand eine
NetSpeakApi (72): bedeutung wennjemand * eine feuchtfrhliche
NetSpeakApi (73): wennjemand eine * feuchtfrhliche party
NetSpeakApi (74): eine auf * der vielalkohol
NetSpeakApi (75): auf der * vielalkohol getrunken
NetSpeakApi (76): der vielalkohol * getrunken wird
NetSpeakApi (77): vielalkohol getrunken * wird dann
NetSpeakApi (78): wenn jemand * eine feuchtfroehliche
NetSpeakApi (79): jemand eine * feuchtfroehliche party
NetSpeakApi (80): eine feuchtfroehliche * party feiert
NetSpeakApi (81): feuchtfroehliche party * feiert also
NetSpeakApi (82): bedeutet im * deutschen naemlich
NetSpeakApi (83): im deutschen * naemlich betrunken
NetSpeakApi (84): deutschen naemlich * betrunken sein
NetSpeakApi (85): deutschen naemlich betrunken * sein
NetSpeakApi (86): deutschen naemlich betrunken sein *
NetSpeakApi (87): wird dann * ist erhinterher
NetSpeakApi (88): dann ist * erhinterher wahrscheinlich
NetSpeakApi (89): ist erhinterher * wahrscheinlich blau
NetSpeakApi (90): erhinterher wahrscheinlich * blau blau
NetSpeakApi (91): ist die * musikrichtung bluesdas
NetSpeakApi (92): die musikrichtung * bluesdas ist
NetSpeakApi (93): musikrichtung bluesdas * ist traurig
NetSpeakApi (94): bluesdas ist * traurig aber
NetSpeakApi (95): wie traurig * oder d
NetSpeakApi (96): traurig oder * d primiert
NetSpeakApi (97): oder d * primiert sein
NetSpeakApi (98): d primiert * sein weltbekannt
NetSpeakApi (99): primiert sein * weltbekannt ist
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 31
	at java.lang.String.substring(String.java:1950)
	at controller.EnsureConstraintsOperation.execute(EnsureConstraintsOperation.java:40)
	at controller.LineBreakOperation.execute(LineBreakOperation.java:107)
	at model.Algorithm.execute(Algorithm.java:127)
	at controller.Main.main(Main.java:48)
Java Result: 1
